---
title: "R Notebook"
output: html_notebook
---

Loading the dataset

```{r, echo=F}

source("../init_settings.R")

```


```{r}

data(rugged)
d <- rugged
d

d$cont_africa <- as.factor(d$cont_africa)

# make log version of outcome
d$log_gdp <- log( d$rgdppc_2000 )
# extract countries with GDP data
dd <- d[ complete.cases(d$rgdppc_2000) , ]
# rescale variables
dd$log_gdp_std <- dd$log_gdp / mean(dd$log_gdp)
dd$rugged_std <- dd$rugged / max(dd$rugged)

dd <- dd %>% select(log_gdp, log_gdp_std, rugged, rugged_std, cont_africa)

```

Simple visualizations
```{r}

dd %>%
  ggplot(aes(x = rugged_std, y = log_gdp_std, col = cont_africa)) +
    geom_point() +
    geom_smooth(method = "lm", se = F)

```

We can clearly see that when the country is in Africa the gdp is directly proportional to ruggedness, else the reverse.

Lets build up the relationship:
1. Modelling only the intercepts

```{r}

mfile <- "models/africa_m1"
# file.remove(paste0(mfile, ".rds"))

# get_prior(data = dd, family = gaussian,
#                  formula = log_gdp_std ~ 1 + (1| cont_africa))

priors <- prior(normal(0, .5), class = Intercept)

africa_m1 <- brm(data = dd, family = gaussian,
                 formula = log_gdp_std ~ 1 + cont_africa,
                 sample_prior = T, prior = priors,
                 cores = 4, chains = 4,
                 control = list(adapt_delta = 0.95,
                                max_treedepth = 15),
                 file = mfile)

```

```{r}
summary(africa_m1)
```



```{r, fig.width=12, fig.height=6}

p1 <- dd %>%
  data_grid(cont_africa) %>%
  add_predicted_draws(africa_m1) %>%
  ggplot(aes(x = .prediction, col = cont_africa, fill = cont_africa)) + geom_density(alpha = 0.2)

p2 <- dd %>%
  ggplot(aes(x = log_gdp_std, col = cont_africa, fill = cont_africa)) + geom_density(alpha = 0.2)

grid.arrange(p1, p2, nrow = 1)
```

```{r}

pp_check(africa_m1)
pp_check(africa_m1, type = "dens")
pp_check(africa_m1, type = "error_hist")
stanplot(africa_m1)

```


```{r}

posterior_samples(africa_m1)

```

```{r}

posterior_samples(africa_m1) %>%
  pivot_longer(names_to = "InterceptTypes",
               values_to = "vals",
               cols = c(b_Intercept, prior_Intercept)) %>%
  ggplot(aes(x = vals, col = InterceptTypes, fill = InterceptTypes)) +
    geom_density(alpha = 0.2) +
    coord_cartesian(ylim = c(0, 5))

```

```{r}

posterior_samples(africa_m1) %>%
  mutate(b_Intercept_africa = b_Intercept + b_cont_africa1) %>%
  pivot_longer(names_to = "InterceptTypes",
               values_to = "vals",
               cols = c(b_Intercept, prior_Intercept, b_Intercept_africa)) %>%
  ggplot(aes(x = vals, col = InterceptTypes, fill = InterceptTypes)) +
    geom_density(alpha = 0.2) #+
    # coord_cartesian(ylim = c(0, 5))

```

Introducing the ruggedness factor
```{r}
mfile <- "models/africa_m2"
file.remove(paste0(mfile, ".rds"))

# get_prior(data = dd, family = gaussian,
#                  formula = log_gdp_std ~ 1 + (1| cont_africa))

priors <- c(prior(normal(0, .5), class = Intercept),
            prior(normal(0, 0.5), class = b))

africa_m2 <- brm(data = dd, family = gaussian,
                 formula = log_gdp_std ~ 1 + cont_africa + rugged_std,
                 sample_prior = T, prior = priors,
                 cores = 4, chains = 4,
                 control = list(adapt_delta = 0.95,
                                max_treedepth = 15),
                 file = mfile)

```

```{r}

new_df <- expand.grid(cont_africa = c(0,1),
                      rugged_std = seq(from = -2, to = 2, length.out = 100)) %>%
          as_tibble()

new_df %>%
  mutate(cont_africa = as.factor(cont_africa)) %>%
  add_predicted_draws(africa_m2) %>%
  ggplot(aes(x = .prediction, col = cont_africa, fill = cont_africa)) +
    geom_density(alpha = 0.2)


```

