Source: https://www.rensvandeschoot.com/tutorials/brms-started/

This tutorial focusses on non-informative priors.

```{r}

library(brms) # for the analysis
library(haven) # to load the SPSS .sav file
library(tidyverse) # needed for data manipulation.
library(RColorBrewer) # needed for some extra colours in one of the graphs
library(ggmcmc)
library(ggthemes)
library(ggridges)
library(bayesplot)
library(tidybayes)
library(modelr)
library(gridExtra)
```

```{r}

popular2data <- read_sav(file = "https://github.com/MultiLevelAnalysis/Datasets-third-edition-Multilevel-book/blob/master/chapter%202/popularity/SPSS/popular2.sav?raw=true")

df <- select(popular2data, pupil, class, extrav, sex, texp, popular) # we select just the variables we will use
head(df) # we have a look at the first 6 observations

df
```

```{r}

ggplot(data  = df,
       aes(x = extrav,
           y = popular,
           col = class,
           group = class))+
  geom_point(size = 1.2,
             alpha = .8,
             position = "jitter")+# to add some random noise for plotting purposes
  theme_minimal()+
  labs(title = "Popularity vs. Extraversion",
       subtitle = "Added a regression line") +
  geom_smooth(method = "lm",
              se = F,
              size = 0.5,
              alpha = 0.8) +
  theme(legend.position = "none") +
  scale_color_gradientn(colours = rainbow(100))

```

Outcome: Popularity and extraversion is not the same for all classes.

Data Analysis:

Building an intercept only model

```{r}

m1 <- brm(
  data = df, family = gaussian,
  formula = popular ~ 1 + extrav,
  chains = 4, cores = 4)


```




```{r}

m1

```

```{r}


mcmc_trace(m1)

p1 <- df %>%
  data_grid(extrav) %>%
  add_fitted_draws(m1) %>%
  ggplot(aes(x = factor(extrav), y = .value)) + geom_boxplot()
  
p2 <- df %>%
  data_grid(extrav) %>%
  add_predicted_draws(m1) %>%
  ggplot(aes(x = factor(extrav), y = .prediction)) + geom_boxplot()

grid.arrange(p1, p2, nrow=1)

```

```{r}

mfile = "models/pop_tut1_m1"

m1 <- brm(
  data = df, family = gaussian,
  formula = popular ~ 1 + (1|class),
  chains = 4, cores = 4,
  file = mfile)


```

```{r}

m1 %>%
  spread_draws(b_Intercept, r_class[class,]) %>%
  median_qi(preds = b_Intercept + r_class) %>%
  ggplot(aes(x = class, y = preds, ymin = .lower, ymax = .upper)) + geom_ribbon()

```

```{r}

df %>%
  data_grid(class) %>%
  add_fitted_draws(m1) %>%
  ggplot(aes(x = class, y = .value)) + geom_point()

```

Adding one level of predictor

```{r}

mfile = "models/pop_tut1_m2"

m2 <- brm(family = gaussian, data = df,
          formula = popular ~ 1 + sex + extrav + (1|class),
          cores = 4, chains = 4,
          file = mfile)

```

```{r}

summary(m2)

```

```{r, fig.width=12}

p1 <- m1 %>%
  spread_draws(b_Intercept, r_class[class,]) %>%
  median_qi(preds = b_Intercept + r_class) %>%
  ggplot(aes(x = class, y = preds, ymin = .lower, ymax = .upper)) +
    geom_ribbon(alpha = 0.4) +
    geom_line() +
    ggtitle("Varying intercepts only model")

p2 <- m2 %>%
  spread_draws(b_Intercept, b_sex, b_extrav, r_class[class,]) %>%
  median_qi(preds = b_Intercept + b_sex + b_extrav + r_class) %>%
  ggplot(aes(x = class, y = preds, ymin = .lower, ymax = .upper)) + 
    geom_ribbon(alpha = 0.4) +
    geom_line() +
    ggtitle("sex, extrav and varying intercepts")

grid.arrange(p1, p2, nrow = 1)

```

Model comparison

```{r}

w1 <- waic(m1)
w2 <- waic(m3)

compare_ic(loo1, loo2)
```


```{r}

mfile = "models/pop_tut1_m3"

m3 <- brm(family = gaussian, data = df,
          formula = popular ~ 1 + sex + extrav + texp + (1|class),
          cores = 4, chains = 4,
          file = mfile)

```



Adding random slopes for both predictor variables (sex, extrav)
```{r}

mfile = "models/pop_tut1_m4"

m4 <- brm(family = gaussian, data = df,
          formula = popular ~ 1 + sex + extrav + (1 + sex + extrav | class),
          cores = 4, chains = 4,
          sample_prior = "yes",
          file = mfile)

```

```{r}

get_variables(m4)

m4 %>%
  spread_draws(b_Intercept, b_sex, b_extrav, r_class[class, sex], r_class[class, extrav])

```
model with interaction between texp and extrav
```{r}

mfile = "models/pop_tut1_m5.rds"

if (file.exists(mfile)) {
  tryCatch({file.remove(mfile)},
           error = function(cond) {
             message(paste0("File doesn't seem to exist: ", mfile))
             message(cond)
           },
           warning = function(cond) {
             message(paste0("File caused a warning: ", mfile))
             message(cond)
           },
           finally = {
             message("Deleted the file: ", mfile)
           })
}


mfile = "models/pop_tut1_m5"

m5 <- brm(family = gaussian, data = df,
          formula = popular ~ 1 + sex + extrav + texp + extrav:texp + (1 + extrav|class),
          cores = 4, chains = 4,
          control = list(adapt_delta = 0.95),
          iter = 14000, warmup = 13000,
          sample_prior = "yes",
          file = mfile)

```

```{r}

get_variables(m5)

summary(m5)$fixed

summary(m5)$random

```


```{r}

m5 %>%
  spread_draws(b_Intercept, r_class[class, sex])

df %>%
  data_grid(class, sex) %>%
  add_fitted_draws(m5) %>%
  group_by(class, sex) %>%
  summarise(lower95 = quantile(.value, probs = 0.025),
            upper95 = quantile(.value, probs = 0.975),
            distance = upper95 - lower95,
            Meanestimate = mean(.value)) %>%
  ggplot(aes(x = class, y = Meanestimate, ymin = lower95, ymax = upper95)) + geom_ribbon() + facet_grid(sex~.)

```





