---
title: "R Notebook"
output: html_notebook
---


```{r, echo=F, include=F}

source("../init_settings.R")

```

Input data
```{r}

mu <- 20
sigma <- 5

```


```{r}

N <- 10
x <- seq(from = 0, to = 10, length.out = N)
y <- rnorm(N, 2 * x, 0.5)

N_pred <- 5
xpred <- seq(from = 0, to = 4, length.out = N_pred)

data <- list(N = N,
             x = x,
             y = y,
             N_pred = N_pred,
             xpred = xpred)

```

```{r}

mod <- cmdstan_model(stan_file = "learn_ppc.stan")

fit <- mod$sample(data = data)
# fit100 <- mod$sample(data = list(N=100, y = rnorm(100, mu, sigma)))
# fit1000 <- mod$sample(data = list(N=1000, y = rnorm(1000, mu, sigma)))

```

```{r}

fit <- stan(file = "learn_ppc.stan", data = data)

```


```{r}
rstan::extract(fit) %>%  str

yrep <- rstan::extract(fit)$yrep
yrep_stn <- rstan::extract(fit)$yrep_stn

```


```{r}

ppc_dens_overlay(y, yrep[1:100,])
ppc_hist(y, yrep[1:10,])

ppc_stat(y, yrep, stat="max")
ppc_stat(y, yrep, stat="min")
ppc_stat(y, yrep, stat="mean")
ppc_stat(y, yrep, stat="sum")
ppc_stat(y, yrep, stat="sd")
ppc_stat(y, yrep, stat="median")

```


```{r}

mu_10 <- fit10$draws()[,,"mu"] %>% as_tibble() %>% 
  pivot_longer(cols = everything(), names_to = "chains", values_to = "mu") %>% 
  mutate(fit="f10")
mu_100 <- fit100$draws()[,,"mu"] %>% as_tibble() %>% 
  pivot_longer(cols = everything(), names_to = "chains", values_to = "mu") %>% 
  mutate(fit="f100")
mu_1000 <- fit1000$draws()[,,"mu"] %>% as_tibble() %>% 
  pivot_longer(cols = everything(), names_to = "chains", values_to = "mu") %>% 
  mutate(fit="f1000")

mu_data <- rbind(mu_10, mu_100, mu_1000)

```

```{r}
sig_10 <- fit10$draws()[,,"sigma"] %>% as_tibble() %>% 
  pivot_longer(cols = everything(), names_to = "chains", values_to = "sigma") %>% 
  mutate(fit="f10")
sig_100 <- fit100$draws()[,,"sigma"] %>% as_tibble() %>% 
  pivot_longer(cols = everything(), names_to = "chains", values_to = "sigma") %>% 
  mutate(fit="f100")
sig_1000 <- fit1000$draws()[,,"sigma"] %>% as_tibble() %>% 
  pivot_longer(cols = everything(), names_to = "chains", values_to = "sigma") %>% 
  mutate(fit="f1000")

sig_data <- rbind(sig_10, sig_100, sig_1000)
```

```{r}

p1 <- mu_data %>% 
  ggplot(aes(x = mu, col = fit, fill = fit)) + geom_density(alpha = 0.2)

p2 <- sig_data %>% 
  ggplot(aes(x = sigma, col = fit, fill = fit)) + geom_density(alpha = 0.2)

grid.arrange(p1, p2, nrow = 1)

```

```{r}


```
