---
title: "R Notebook"
output: html_notebook
---


```{r, echo=F, include=F}

source("../init_settings.R")

```

Simulating a 2 cluster gaussian mixture model

```{r}

data_list <- list(
  lambda = 0.5,
  mu = c(3,-3),
  sigma = c(1,1)
)

m1 <- stan(file = "simp_mix_1.stan",
           data = data_list,
           iter = 40000, warmup = 30000)

```

```{r}

rstan::extract(m1) %>% as_tibble() %>% 
  ggplot(aes(x = y)) + geom_density() + xlim(c(-10,10))

```

```{r, fig.height=6, fig.width=12}
rstan::extract(m1,
               permuted = FALSE,
               inc_warmup = TRUE,
               pars = c("lp__"),
               include = FALSE) %>%
  as_tibble() %>%
  select(ends_with("y")) %>% 
  mutate(draws = row_number()) %>% 
  pivot_longer(cols = -draws, names_to = "chains", values_to = "y") %>% 
  ggplot(aes(x = draws, y = y, col = chains)) +
    geom_line() +
    geom_vline(xintercept = 20000) +
    facet_grid(.~chains) +
    theme(axis.text.x = element_text(hjust=1, angle = 45))
```

```{r}
rstan::extract(m1) %>% as_tibble() %>% 
  ggplot(aes(x = y)) + geom_density() + xlim(c(-10,10))

```

```{r}
data_list <- list(x = as.numeric(c(1.,2.,3.)))
m <- stan(file = "test.stan",
          iter = 1, chains = 1,
          algorithm = "Fixed_param",
          data = data_list)

t(rstan::extract(m)$y_smax)

y <- 1:3

exp(y)/sum(exp(y))

```

```{r}
data_list <- list(N = 100)#, theta = c(0.1,0.2,0.7))
m <- stan(file = "test.stan",
          iter = 1, chains = 1,
          algorithm = "Fixed_param",
          data = data_list)

```

```{r}
alpha <- c(0,3, 0.7)
data_list <- list(N_params = length(alpha), alpha = alpha, num_samples = 100)
m <- stan(file = "test.stan",
          iter = 1, chains = 1,
          algorithm = "Fixed_param",
          data = data_list)

```

```{r}

plot(t(rstan::extract(m)$theta))
```

```{r}
# require(MCMCpack)
round(rdirichlet(5, c(1e2, 1e2)),2)
```


```{r}
data_list <- list(
  alpha = 0.3,
  num_param_dims = 5,
  num_dist_draws_per_pgrp = 30,
  num_simplex_per_dist = 20,
  num_draws_from_simplex = 15
)

m <- stan(file = "test.stan",
          iter = 1, chains = 1,
          algorithm = "Fixed_param",
          data = data_list)

```

```{r}
rstan::extract(m)$theta_mat[,,]

rstan::extract(m)$final_samples[,,]
```

```{r}

alpha <- 1
num_param_dims <- 5
num_dist_draws_per_pgrp <- 5
num_simplex_per_dist <- 30
num_draws_from_simplex <- 15
mu <- c(1e0, 1e1, 1e2, 1e3, 1e4)
sigma <- c(0.1, 0.1, 0.1, 0.1, 0.1)
  
data_list <- list(num_param_dims = num_param_dims,
                  alpha = alpha,
                  num_dist_draws_per_pgrp = num_dist_draws_per_pgrp,
                  num_simplex_per_dist = num_simplex_per_dist,
                  num_draws_from_simplex = num_draws_from_simplex,
                  mu = mu,
                  sigma = sigma)
m <- stan(file = "mixture-models.stan",
          iter = 1, chains = 1,
          algorithm = "Fixed_param",
          data = data_list)

```

```{r}
rstan::extract(m)$theta_mat[,,]

rstan::extract(m)$final_samples[,,]

rstan::extract(m)$sim_samples[,,]
```
